image: node:lts

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
  - node_modules/

before_script:
  - apt-get -y update
  - apt-get -y install jq
  - wget https://api.github.com/repos/gohugoio/hugo/releases/latest -O - | jq -r '.assets[] | select(.name | index("Linux-64bit.tar.gz")) | .browser_download_url' | wget -i -
  - tar -xzf hugo_extended*.tar.gz --directory /usr/local/bin
  - chmod +x /usr/local/bin/hugo
  - yarn

test:
  script:
  - yarn webpack --mode development
  - hugo
  except:
  - master

pages:
  script:
  - yarn webpack --mode production
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
